# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

cache: npm

branches:
  only:
    - master

env:
  global:
    - GO111MODULE=on

jobs:
  include:
    - name: "Config Builder Tests"
      language: go
      go: 1.13.x
      script:
        - cd cfgBuilder
        - make lint
        - go test ./...
    - name: "cb-sol-cli Tests"
      language: node_js
      node_js: 12
      env: CI=true
      script:
        - pushd cb-sol-cli
        - make install
        - cd chainbridge-solidity && SILENT=true make start-ganache
        - popd && ./ci/ci_cli.sh
    - name: "Deploy Tester Tests"
      language: go
      go: 1.13.x
      script:
        - set -e
        - docker-compose -f ./docker-compose-e2e.yml up -d
        - docker ps
        - travis_wait 30 cd deploy-test
        - make test
